language : python
python :
   - "3.5"
cache:
    pip : true
    directories :
        - $HOME/.pip-cache/
install :
    -  pip install -r travis_requirements.txt --download-cache $HOME/.pip-cache
script :
  - python mosaicer/retrain.py --how_many_training_steps=10
  - python mosaicer/mosaicer.py test.avi